title: Portfolio Julien Sebag
email: julien.sebag@me.com
description: Portfolio of Julien Sebag, UX / UI / Web Designer based in Warsaw, Poland.
baseurl: "/"
url: ""
cv: resume-juliensebag.pdf
picture: picture-julien-sebag.jpg
favicon: favicon.png
cover_og: cover-og.png

markdown: kramdown

collections:
  projects:
    output: true
    # permalink: /:name/
  templates:
    output: false

sass:
    style: compressed
    sass_dir: _sass

permalink: /:projects/:name/

plugins:
  - jekyll-multiple-languages-plugin

languages: ["en", "fr"]
exclude_from_localizations: ["javascript", "images", "css"]
defaultLang: en
languageNames:
  fr: Fran√ßais
  en: English

defaults:
  -
    scope:
      type: projects
    values:
      layout: projects
  -
    scope:
      path: ""
    values:
      layout: "default"